### ISSUE TITLE
UI: Edit modes

### ISSUE THREAD

**Issue by j3k0** [j3k0/logbookr#11]
##### Situation

There's an inconsistency between screens in the way it allows edition.
- Choicetree
  - Opens in **read-only mode**.
  - Click `Edit` to make changes.
  - Changes are **saved automatically**.
- Template
  - Opens in **edit mode**.
  - Changes are **saved automatically**.
  - Clicking `back` &rArr; changes are saved.
- Procedures
  - Open in **edit mode**.
  - Changes are saved by clicking `Save`.
  - Clicking `back` &rArr; changes are lost.
##### Suggestion
- Template and Procedure open in **read-only** mode. (HTML `readonly` attribute)
  - Click `Edit` to make changes.
  - Click `Save` to save, `Cancel` to revert.
- While in **edit mode**, it's not possible to hit `Back`
  - Top bar replaced with cancel/save buttons.

**Comment by elmigranto** [comment]
What happens when user clicks hardware "Back" button on a device while in "Edit" mode?

**Comment by j3k0** [comment]
Well, what's the latest standard behavior for that on Android? We should probably use the same behavior.

**Comment by elmigranto** [comment]
I meant what Cordova will do, nothing unless we specify or will it go back like in a browser? Because we can swap `< Go Back` to Save/Cancel but will user be "protected" from clicking phone's hardware back button?

The reasonable thing could be:
- to show a warning about unsaved changes (easiest);
- save clone, but don't apply changes, and suggest to restore them when switching back to edit mode on the same procedure (a lot of details to take care of here);
- some sort of combination of both.

**Comment by j3k0** [comment]
Default cordova behavior for the "back" event is to proceed as a browser would. However, it's possible to intercept the event and prevent the default behavior if required. In our setup, if it exists we call the "goBack()" function of the current view (if not, proceed with default behavior).
- Show a "are you sure?" warning about unsaved changes, best way in my opinion.

**Comment by elmigranto** [comment]
Pushed for procedures (somewhat messy template-wise though); would be glad if you checked it out, so I can be sure this is what you had in mind.

**Comment by j3k0** [comment]
okay, will do.

**Comment by j3k0** [comment]
That's almost it.
- Once `discard` has been clicked &rArr;
  - Clicking `Edit` should show the data at initial state, not the discarded one.
  - Clicking `Back` shouldn't display a warning.
- Clicking `discard` should show the warning that appears when hitting `Back` for now (if relevant).
- `save` and `discard` will have to cover the top bar, but that'll be Cristina's concern (CSS-girl).

I think that's easy to fix. Please ask if you are unsure.

**Comment by elmigranto** [comment]
So this should be the case:
- open procedure with patient "X";
- click edit, change name to "XXX";
- without saving changes, click discard;
- name should revert to "X".

**Comment by j3k0** [comment]
Exactly. Long version:
1. click procedure "X"
2. procedure opens in read-only mode
3. click edit
4. procedure opens in write mode
5. change name to "XXX"
6. click discard
7. dialog box "confirm discard?" appears
8. click YES
9. name revert to "X", procedure opens in read-only mode
10. click edit
11. procedure opens in write mode. name is "X". name is NOT "XXX".
12. click discard &rarr; confirm dialog DO NOT appear (because no change were made)
13. click back &rarr; NO dialog box either.

Hope we're on the same page.

**Comment by elmigranto** [comment]
Fixed flow according to this and added show/edit modes for template editor.

**Comment by j3k0** [comment]
That's great. Good job!

**Comment by j3k0** [comment]
**Issue remaining**

Discarding a **new** procedure should get back to the list of procedures.

**To reproduce**
1. from procedures list, click `Add new procedure`
2. from procedureEditView, click `discard`

Outcome: procedureShowView is shown.
Expected: go back to procedures list
